import Foundation
import Testing
@testable import SeamlessTransitions

@Suite struct BeatAnalyzerTests {
    private func untrimmed(_ url: URL) throws -> TrimInfo {
        let t = try #require(try SilenceDetector.detect(url: url))
        return t
    }

    /// Asserts bpm, per-beat time error and downbeat phase for a click track generated by TestAudio.
    private func verify(_ info: BeatInfo, _ ct: ClickTrack, sourceLocation: SourceLocation = #_sourceLocation) {
        #expect(abs(info.bpm - ct.bpm) <= 0.05, "bpm \(info.bpm) vs \(ct.bpm)", sourceLocation: sourceLocation)
        #expect(info.confidence >= BeatInfo.minConfidence, sourceLocation: sourceLocation)
        for (name, beats, db) in [("head", info.headBeats, info.headDownbeatIndex), ("tail", info.tailBeats, info.tailDownbeatIndex)] {
            #expect(beats.count >= 8, "\(name) count", sourceLocation: sourceLocation)
            var worst = 0.0
            for b in beats {
                let k = ct.beatIndex(near: b)
                worst = max(worst, abs(b - ct.beatTime(k)))
            }
            #expect(worst <= 0.003, "\(name) worst beat error \(worst * 1000) ms", sourceLocation: sourceLocation)
            if db < beats.count {
                #expect(ct.beatIndex(near: beats[db]) % 4 == 0, "\(name) downbeat index \(db) is beat \(ct.beatIndex(near: beats[db]))", sourceLocation: sourceLocation)
            } else {
                Issue.record("\(name) downbeat index out of range", sourceLocation: sourceLocation)
            }
        }
        #expect(zip(info.headBeats, info.headBeats.dropFirst()).allSatisfy { $0 < $1 })
        #expect(zip(info.tailBeats, info.tailBeats.dropFirst()).allSatisfy { $0 < $1 })
    }

    @Test(arguments: [(90.0, 90.0), (124.0, 70.0), (128.0, 70.0), (174.0, 60.0)])
    func clickTrackTempoBeatsDownbeat(bpm: Double, seconds: Double) throws {
        let d = TempDir(name: "beat")
        let ct = try TestAudio.writeClickTrack(to: d.file("c.wav"), bpm: bpm, seconds: seconds, hats: bpm == 128)
        let trim = try untrimmed(ct.url)
        let info = try #require(try BeatAnalyzer.analyze(url: ct.url, trim: trim))
        verify(info, ct)
    }

    @Test func beatsAreInFileTimeWithLeadingSilenceAndStereo48k() throws {
        let d = TempDir(name: "beat")
        let ct = try TestAudio.writeClickTrack(to: d.file("c.caf"), bpm: 126, seconds: 60, sampleRate: 48000, channels: 2,
                                               leading: 3.2, trailing: 2.0, firstBeat: 0.41)
        let trim = try untrimmed(ct.url)
        #expect(abs(trim.startSeconds - ct.firstBeat) < 0.02)
        let info = try #require(try BeatAnalyzer.analyze(url: ct.url, trim: trim))
        verify(info, ct)
        #expect(info.headBeats.first! >= trim.startSeconds - 0.01)
        #expect(info.tailBeats.last! <= trim.endSeconds + 0.01)
    }

    @Test func smoothToneClicksWithBedAreTracked() throws {
        let d = TempDir(name: "beat")
        let ct = try TestAudio.writeClickTrack(to: d.file("c.wav"), bpm: 124, seconds: 60, kind: .tone2k, bed: 0.05)
        let info = try #require(try BeatAnalyzer.analyze(url: ct.url, trim: try untrimmed(ct.url)))
        verify(info, ct)
    }

    @Test func whiteNoiseHasNoBeat() throws {
        let d = TempDir(name: "beat")
        let u = d.file("n.wav")
        try TestAudio.write([TestAudio.noise(rmsDB: -20, sampleRate: 44100, seconds: 40)], sampleRate: 44100, to: u)
        #expect(try BeatAnalyzer.analyze(url: u, trim: try untrimmed(u)) == nil)
    }

    @Test func speechLikeHasNoBeat() throws {
        let d = TempDir(name: "beat")
        let u = d.file("s.wav")
        try TestAudio.write([TestAudio.speechLike(sampleRate: 44100, seconds: 60)], sampleRate: 44100, to: u)
        #expect(try BeatAnalyzer.analyze(url: u, trim: try untrimmed(u)) == nil)
    }

    @Test func steadySineHasNoBeat() throws {
        let d = TempDir(name: "beat")
        let u = d.file("s.wav")
        try TestAudio.writeSine(to: u, seconds: 40)
        #expect(try BeatAnalyzer.analyze(url: u, trim: try untrimmed(u)) == nil)
    }

    @Test func tooShortRegionIsNil() throws {
        let d = TempDir(name: "beat")
        let ct = try TestAudio.writeClickTrack(to: d.file("c.wav"), bpm: 120, seconds: 15)
        #expect(try BeatAnalyzer.analyze(url: ct.url, trim: try untrimmed(ct.url)) == nil)
    }
}
